-- Expand the editor-backed public copy for the full TPLG site.
-- URLs, images and publication links remain code-managed.
insert into public.site_content (content_key, page, label, content_value, sort_order)
values
  ('people.heading.main', 'People', 'Heading', 'Experienced political counsel,', 0),
  ('people.heading.emphasis', 'People', 'Heading emphasis', 'directly engaged.', 1),
  ('people.lede', 'People', 'Introduction', 'Clients work with people who know their organizations, understand their priorities and are accessible when decisions need to be made.', 2),
  ('people.nonattorney.note', 'People', 'Non-attorney note', '*Denotes a non-attorney professional.', 3),
  ('people.nicholas.name', 'Nicholas Sanders', 'Name', 'Nicholas Sanders', 4),
  ('people.nicholas.role', 'Nicholas Sanders', 'Role', 'Founding Partner', 5),
  ('people.nicholas.intro', 'Nicholas Sanders', 'Introduction', 'Nicholas Sanders is a founding partner of The Political Law Group, where he advises candidates, public officials, political committees, ballot measure campaigns, nonprofit organizations and political professionals on the laws governing campaigns, elections, political advocacy, lobbying and government ethics.', 6),
  ('people.nicholas.bio.1', 'Nicholas Sanders', 'Biography, paragraph 1', 'Nick serves as general counsel to campaigns and political organizations and advises clients on the legal issues that arise throughout the lifecycle of political activity, from formation, fundraising and campaign communications to ballot access, regulatory compliance and enforcement. He has drafted dozens of ballot measures and counseled candidates and public officials throughout California, bringing a practical understanding of how legal requirements intersect with political strategy and day-to-day campaign operations.', 7),
  ('people.nicholas.bio.2', 'Nicholas Sanders', 'Biography, paragraph 2', 'Nick also maintains an active election law and litigation practice. He has successfully protected candidates’ ballot access, ballot designations and candidate statements and challenged ballot materials and measures that failed to comply with governing law.', 8),
  ('people.nicholas.bio.3', 'Nicholas Sanders', 'Biography, paragraph 3', 'Nick brings more than 15 years of political law experience, including private practice focused on political and election law and service at both the California Fair Political Practices Commission and the Federal Election Commission. His experience inside the agencies that administer and enforce campaign finance laws informs a practical, solutions-oriented approach to compliance, enforcement and political risk.', 9),
  ('people.nicholas.education', 'Nicholas Sanders', 'Education', 'University of California, Davis School of Law, J.D., 2015
University of California, Davis, B.A., 2008', 10),
  ('people.nicholas.admissions', 'Nicholas Sanders', 'Admissions', 'California', 11),
  ('people.nicholas.email', 'Nicholas Sanders', 'Email', 'nicholas@tpl.group', 12),
  ('people.tracey.name', 'Tracey Frazier Wigglesworth', 'Name', 'Tracey Frazier Wigglesworth', 13),
  ('people.tracey.role', 'Tracey Frazier Wigglesworth', 'Role', 'Founding Partner', 14),
  ('people.tracey.intro', 'Tracey Frazier Wigglesworth', 'Introduction', 'Tracey Frazier Wigglesworth is a founding partner of The Political Law Group, where her practice includes advising nonprofit and corporate clients, candidates, committees and major donors on campaign finance compliance, political and issue advocacy, lobbying, government contracts and conflicts of interest.', 15),
  ('people.tracey.bio.1', 'Tracey Frazier Wigglesworth', 'Biography, paragraph 1', 'Drawing on deep experience in both the public and private sectors, Tracey advises clients on risk management and strategic defense in sensitive audits, investigations and complex compliance matters. She has defended clients in administrative enforcement actions before federal, state and local regulators across the country.', 16),
  ('people.tracey.bio.2', 'Tracey Frazier Wigglesworth', 'Biography, paragraph 2', 'Tracey also advises political technology startups, established companies and platforms on emerging issues at the intersection of law, politics and technology. She helps clients navigate election, ethics, contracting and disclosure laws as they develop new technology or business models, enter the political space and bring innovative products to market in California and nationwide.', 17),
  ('people.tracey.bio.3', 'Tracey Frazier Wigglesworth', 'Biography, paragraph 3', 'Before co-founding TPLG, Tracey split her time between Sacramento, Los Angeles and Washington, D.C., where she helped build and oversee one of the country’s largest nonfederal campaign finance compliance programs; advise Fortune 100 corporations on 50-state political giving; and investigate, prosecute, negotiate and resolve more than 1,700 matters involving alleged violations of campaign finance, lobbying and government ethics laws.', 18),
  ('people.tracey.education', 'Tracey Frazier Wigglesworth', 'Education', 'University of the Pacific, McGeorge School of Law, J.D., 2015; Certificate in Public Law and Policy
Loyola Marymount University, B.B.A., 2008', 19),
  ('people.tracey.admissions', 'Tracey Frazier Wigglesworth', 'Admissions', 'California', 20),
  ('people.tracey.email', 'Tracey Frazier Wigglesworth', 'Email', 'tracey@tpl.group', 21),
  ('people.emma.name', 'Emma Olson Sharkey', 'Name', 'Emma Olson Sharkey', 22),
  ('people.emma.role', 'Emma Olson Sharkey', 'Role', 'Partner', 23),
  ('people.emma.intro', 'Emma Olson Sharkey', 'Introduction', 'Emma Olson Sharkey is a partner at The Political Law Group and a nationally recognized ballot measure and nonprofit tax lawyer. She advises ballot measure campaigns, nonprofit organizations, political committees and other advocacy organizations on campaign finance, tax and election laws governing political and issue advocacy across the country.', 24),
  ('people.emma.bio.1', 'Emma Olson Sharkey', 'Biography, paragraph 1', 'Emma has served as outside counsel to ballot measure efforts in more than 15 states, advising clients throughout the initiative process, from campaign formation and qualification through post-election proceedings. She counsels campaigns on political and campaign finance laws, defends clients before state regulatory agencies and advises on ballot measure litigation strategy. She also serves as outside counsel to nonprofit organizations and political committees, helping clients structure and conduct political and issue advocacy consistent with federal tax law and state and federal campaign finance requirements.', 25),
  ('people.emma.bio.2', 'Emma Olson Sharkey', 'Biography, paragraph 2', 'A recognized authority on ballot measure law, Emma''s work and commentary have appeared in or been cited by national and political media including The New York Times, The Washington Post, NBC News, TIME, The Hill, Slate, CBS News Radio and Democracy Docket.', 26),
  ('people.emma.bio.3', 'Emma Olson Sharkey', 'Biography, paragraph 3', 'Prior to joining TPLG, Emma was a partner at Elias Law Group, where she advised nonprofit organizations, campaigns and political committees on political law matters nationwide.', 27),
  ('people.emma.education', 'Emma Olson Sharkey', 'Education', 'Northwestern Law School, J.D., 2015
University of Minnesota, B.A., 2008', 28),
  ('people.emma.admissions', 'Emma Olson Sharkey', 'Admissions', 'District of Columbia
Illinois', 29),
  ('people.emma.email', 'Emma Olson Sharkey', 'Email', 'emma@tpl.group', 30),
  ('people.buddy.name', 'Buddy Norton', 'Name', 'Buddy Norton', 31),
  ('people.buddy.role', 'Buddy Norton', 'Role', 'Associate Attorney', 32),
  ('people.buddy.intro', 'Buddy Norton', 'Introduction', 'Buddy Norton is an associate attorney at The Political Law Group, where he advises clients on campaign finance, lobbying, government ethics and election law matters at the federal, state and local levels.', 33),
  ('people.buddy.bio.1', 'Buddy Norton', 'Biography, paragraph 1', 'Buddy brings a broad perspective to his political law practice, informed by work in private practice, government, campaigns and political organizations. He has significant experience in election administration and voter protection, including service as Deputy Director of Voter Protection for a state political party. There, he helped design and implement statewide programs spanning voter education, poll observation, ballot monitoring, voter hotlines and election response teams. During law school, he worked with a national political party’s voter protection program, tracking regulatory, legislative and judicial developments affecting federal and state elections and assisting state parties with voter protection programs during the 2020 election cycle.', 34),
  ('people.buddy.bio.2', 'Buddy Norton', 'Biography, paragraph 2', 'Buddy’s background also includes political organizing and ballot measure campaigns, federal public defense, service in the office of a United States Senator and an externship with the Arizona Supreme Court.', 35),
  ('people.buddy.bio.3', 'Buddy Norton', 'Biography, paragraph 3', 'Prior to joining TPLG, Buddy served as outside political law counsel to a range of local, state and national clients, advising on federal, state and local campaign finance and lobbying compliance, procurement, government ethics and election law requirements.', 36),
  ('people.buddy.education', 'Buddy Norton', 'Education', 'Sandra Day O’Connor College of Law at Arizona State University, J.D., 2021
University of California, Berkeley, B.A., 2015', 37),
  ('people.buddy.admissions', 'Buddy Norton', 'Admissions', 'California', 38),
  ('people.buddy.email', 'Buddy Norton', 'Email', 'buddy@tpl.group', 39),
  ('people.graham.name', 'Graham Willard', 'Name', 'Graham Willard', 40),
  ('people.graham.role', 'Graham Willard', 'Role', 'Associate Attorney', 41),
  ('people.graham.intro', 'Graham Willard', 'Introduction', 'Graham Willard is an associate attorney at The Political Law Group, where his practice focuses on campaign finance, government ethics, election law and regulatory compliance and enforcement.', 42),
  ('people.graham.bio.1', 'Graham Willard', 'Biography, paragraph 1', 'Graham’s unique background spans law, politics and government investigations. Before law school, he spent three years with a national public opinion research and political consulting firm, conducting polling, research and focus groups for political campaigns and advocacy organizations, including work on consequential congressional races during the 2020 election cycle. He later served as an intelligence analyst in the FBI’s Public Corruption Unit.', 43),
  ('people.graham.bio.2', 'Graham Willard', 'Biography, paragraph 2', 'During law school, Graham clerked for a local ethics commission where he helped investigate potential violations of campaign finance, conflicts of interest and ethics laws, evaluated complaints and assisted with enforcement matters. He also interned for a City Attorney’s office where he drafted legislation, analyzed legal risk and advised on compliance with federal, state and local law.', 44),
  ('people.graham.bio.3', 'Graham Willard', 'Biography, paragraph 3', 'Prior to joining TPLG, Graham served as a law clerk to a Los Angeles County Superior Court judge in the writs and receivers department, where he researched and analyzed complex civil matters, including election law writ petitions, and prepared recommendations on matters before the court.', 45),
  ('people.graham.education', 'Graham Willard', 'Education', 'University of California College of the Law, San Francisco, J.D., 2025
Georgetown University, B.S., 2018', 46),
  ('people.graham.admissions', 'Graham Willard', 'Admissions', 'California', 47),
  ('people.graham.email', 'Graham Willard', 'Email', 'graham@tpl.group', 48),
  ('people.kristen.name', 'Kristen Lippstreu', 'Name', 'Kristen Lippstreu', 49),
  ('people.kristen.role', 'Kristen Lippstreu', 'Role', 'Director, Political Compliance', 50),
  ('people.kristen.intro', 'Kristen Lippstreu', 'Introduction', 'Kristen Lippstreu is the Director of Political Compliance at The Political Law Group, where she works with clients to build and manage sophisticated campaign finance, lobbying and political compliance programs across federal, state and local jurisdictions. She brings more than a decade of experience managing complex, high-volume reporting and disclosure obligations for corporations, advocacy organizations and other politically active entities.', 51),
  ('people.kristen.bio.1', 'Kristen Lippstreu', 'Biography, paragraph 1', 'Kristen’s experience spans multistate campaign finance and lobbying programs, PAC administration, major ballot measure campaigns and institution-wide political compliance. She has built compliance programs from the ground up and overseen reporting for significant statewide political spending and large institutions operating across multiple jurisdictions.', 52),
  ('people.kristen.bio.2', 'Kristen Lippstreu', 'Biography, paragraph 2', 'Kristen works closely with clients and counsel to translate complex legal requirements into practical clearance procedures, reporting systems and internal controls. Her combination of technical expertise, operational experience and practical judgment helps clients integrate compliance into their broader political engagement programs while managing risk, improving accuracy and meeting demanding reporting obligations.', 53),
  ('people.kristen.education', 'Kristen Lippstreu', 'Education', 'University of Oregon, B.A., 2012', 54),
  ('people.kristen.email', 'Kristen Lippstreu', 'Email', 'kristen@tpl.group', 55),
  ('people.lauren.name', 'Lauren Deutsch', 'Name', 'Lauren Deutsch', 56),
  ('people.lauren.role', 'Lauren Deutsch', 'Role', 'Compliance Specialist', 57),
  ('people.lauren.intro', 'Lauren Deutsch', 'Introduction', 'Lauren Deutsch is a Compliance Specialist at The Political Law Group, where she supports clients with day-to-day federal and state campaign finance compliance, including preparing reports, maintaining client records and assisting with ongoing reporting obligations.', 58),
  ('people.lauren.bio.1', 'Lauren Deutsch', 'Biography, paragraph 1', 'Lauren’s background includes political fundraising, congressional constituent services and legislative advocacy. Prior to joining TPLG, she supported fundraising programs for federal candidates, working with campaign and donor data, fundraising communications and event operations. She has also worked in a congressional district office and for a statewide advocacy organization, gaining experience with constituent casework, legislative developments and grassroots advocacy programs.', 59),
  ('people.lauren.education', 'Lauren Deutsch', 'Education', 'University of California, Davis, B.A., 2026', 60),
  ('people.lauren.email', 'Lauren Deutsch', 'Email', 'lauren@tpl.group', 61),
  ('people.sara.name', 'Sara Michels', 'Name', 'Sara Michels', 62),
  ('people.sara.role', 'Sara Michels', 'Role', 'Compliance Specialist', 63),
  ('people.sara.intro', 'Sara Michels', 'Introduction', 'Sara Michels is a Compliance Specialist at The Political Law Group, where she supports the firm’s political compliance practice and assists with campaign finance reporting, research and regulatory requirements.', 64),
  ('people.sara.bio.1', 'Sara Michels', 'Biography, paragraph 1', 'Sara brings a background in political science, policy research, data analysis and administrative operations. Her graduate research focused on the relationship between state politics and education policy and included compiling, validating and analyzing financial and policy data from multiple public sources. She also brings experience with financial tracking, reporting and compliance-focused recordkeeping, including managing the budget and financial operations of a large membership organization.', 65),
  ('people.sara.education', 'Sara Michels', 'Education', 'California State University, Sacramento, M.A., 2025
California State University, Fresno, B.A., 2022, magna cum laude', 66),
  ('people.sara.email', 'Sara Michels', 'Email', 'sara@tpl.group', 67),
  ('people.katie.name', 'Katie Clyde', 'Name', 'Katie Clyde', 68),
  ('people.katie.role', 'Katie Clyde', 'Role', 'Director, Operations', 69),
  ('people.katie.intro', 'Katie Clyde', 'Introduction', 'Katie Clyde is the Director of Operations at The Political Law Group, where she oversees the firm’s administrative, financial and business operations. She brings more than 20 years of experience in procurement, finance and project management and works closely with the firm’s partners and professional staff to develop and maintain the systems and processes that support TPLG’s legal and compliance practices.', 70),
  ('people.katie.bio.1', 'Katie Clyde', 'Biography, paragraph 1', 'Before joining TPLG, Katie worked in both the private and public sectors, including with a Sacramento-based lobbying firm and the State of California. Her background includes government contracting, conflicts-of-interest matters and Statements of Economic Interests (Form 700), giving her a practical understanding of the regulatory environment in which many of TPLG’s clients operate.', 71),
  ('people.katie.education', 'Katie Clyde', 'Education', 'California State University, Chico', 72),
  ('people.katie.email', 'Katie Clyde', 'Email', 'katie@tpl.group', 73),
  ('why.heading.main', 'Firm', 'Heading', 'Political law is not one of our practice areas.', 74),
  ('why.heading.emphasis', 'Firm', 'Heading emphasis', 'It is our practice.', 75),
  ('why.body.1', 'Firm', 'Paragraph 1', 'The Political Law Group is a national political law firm built to counsel clients operating at the intersection of law, politics and public policy. Our lawyers bring decades of experience advising candidates, public officials, ballot measure campaigns, political committees, nonprofit and advocacy organizations, corporations and major donors through the legal and regulatory complexities that accompany political engagement.', 76),
  ('why.body.2', 'Firm', 'Paragraph 2', 'With that experience comes an appreciation that political matters rarely present purely legal questions – they implicate larger, strategic decisions that impact communications, fundraising, coalition-building and organizational priorities. Effective counsel requires an understanding of the law and the broader context, identifying and contextualizing risk and providing clear, practical advice that allows clients to make informed decisions.', 77),
  ('why.body.3', 'Firm', 'Paragraph 3', 'It also requires applying established law to a political world that is constantly evolving. Many of the regulatory frameworks governing political activity were developed decades ago, long before today’s methods of campaigning, advocacy, fundraising, communications and technology. We bring deep institutional knowledge to modern problems, with a practical approach focused on finding creative, compliant paths forward.', 78),
  ('why.body.4', 'Firm', 'Paragraph 4', 'Our experience on both sides of the regulatory process adds another dimension to that judgment. We understand how regulators think, where scrutiny is likely to arise and how decisions made in real time may be viewed later. That perspective helps us distinguish meaningful from theoretical risk in real time and strategically respond to government inquiries, investigations and complaints.', 79),
  ('why.body.5', 'Firm', 'Paragraph 5', 'TPLG was built around this approach to political law: deep experience and sound judgment, delivered through a client service model designed for the way our clients operate today. Clients work directly with experienced political lawyers who know their organizations, understand their priorities and are accessible when decisions need to be made. The result is counsel that is rigorous without being rigid, practical without being simplistic and responsive to both where the law has been and where the political process is going.', 80),
  ('practice.campaign-finance.name', 'Practice', 'Campaign Finance: name', 'Campaign Finance', 81),
  ('practice.campaign-finance.description', 'Practice', 'Campaign Finance: summary', 'Formation, fundraising, communications, coordination, disclosure and ongoing compliance.', 82),
  ('practice.elections.name', 'Practice', 'Elections: name', 'Elections', 83),
  ('practice.elections.description', 'Practice', 'Elections: summary', 'Ballot access, ballot measures, candidate materials, disputes and political litigation.', 84),
  ('practice.advocacy.name', 'Practice', 'Advocacy: name', 'Advocacy', 85),
  ('practice.advocacy.description', 'Practice', 'Advocacy: summary', 'Political and issue advocacy programs structured to operate confidently across jurisdictions.', 86),
  ('practice.nonprofits.name', 'Practice', 'Nonprofits: name', 'Nonprofits', 87),
  ('practice.nonprofits.description', 'Practice', 'Nonprofits: summary', 'Tax, campaign finance and election-law guidance for nonprofit political and issue advocacy.', 88),
  ('practice.ethics.name', 'Practice', 'Ethics: name', 'Ethics', 89),
  ('practice.ethics.description', 'Practice', 'Ethics: summary', 'Lobbying, government ethics and disclosure guidance for public and private actors.', 90),
  ('practice.enforcement.name', 'Practice', 'Enforcement: name', 'Enforcement', 91),
  ('practice.enforcement.description', 'Practice', 'Enforcement: summary', 'Strategic representation in audits, investigations and agency enforcement matters.', 92),
  ('practice.campaign-finance.body.1', 'Campaign Finance details', 'Paragraph 1', 'TPLG advises candidates, political committees, corporations, nonprofit organizations, trade associations, major donors and other participants in the political process on campaign finance laws at the federal, state and local levels. We counsel clients on committee formation, fundraising and contribution limits, political spending, independent expenditures, coordination, advertising and communications, disclosure and the increasingly complex rules governing political activity across jurisdictions. Federal and California law both regulate political fundraising, spending and disclosure through detailed reporting and substantive requirements.', 93),
  ('practice.campaign-finance.body.2', 'Campaign Finance details', 'Paragraph 2', 'Our lawyers frequently serve as outside general counsel to campaigns and political organizations, working alongside our compliance professionals to provide integrated legal and reporting support. TPLG’s compliance team manages committee registrations, campaign finance reports, reconciliations and day-to-day reporting obligations, while our lawyers advise on the legal and strategic questions that arise as campaigns and political programs evolve.', 94),
  ('practice.campaign-finance.body.3', 'Campaign Finance details', 'Paragraph 3', 'We also counsel corporations, nonprofits and emerging political businesses on political giving programs, pay-to-play restrictions, campaign advertising and disclosure, and new products or business models that implicate campaign finance laws.', 95),
  ('practice.elections.body.1', 'Elections details', 'Paragraph 1', 'TPLG advises candidates, campaigns, ballot measure committees, public agencies and other participants in the electoral process on the laws governing access to and participation in elections. Our work spans candidate qualifications and ballot access, ballot designations and candidate statements, initiative drafting and qualification, election administration and disputes arising before and after Election Day.', 96),
  ('practice.elections.body.2', 'Elections details', 'Paragraph 2', 'Our ballot measure practice provides counsel throughout the initiative process. We advise proponents, opponents, funders and committees on drafting and qualification, campaign structure, disclosure and compliance, legal strategy and post-election proceedings. Where disputes require litigation, our lawyers prosecute and defend challenges involving candidates, ballot materials, measures and other election-law questions.', 97),
  ('practice.elections.body.3', 'Elections details', 'Paragraph 3', 'We bring the same approach to election disputes that informs the rest of our practice: deep knowledge of the governing law, an understanding of the political context in which the dispute is unfolding and practical advice about the consequences of decisions made under compressed timelines.', 98),
  ('practice.advocacy.body.1', 'Advocacy details', 'Paragraph 1', 'TPLG helps corporations, nonprofit organizations, trade associations, advocacy groups and political professionals design and execute sophisticated political and issue advocacy programs. We advise on the legal frameworks governing communications, grassroots activity, independent expenditures, political giving, coalition activity and other efforts to influence public policy and the political process.', 99),
  ('practice.advocacy.body.2', 'Advocacy details', 'Paragraph 2', 'For organizations operating nationally, we help identify when activity triggers campaign finance, lobbying, disclosure, pay-to-play or other regulatory requirements and develop structures that can function across multiple jurisdictions. For political technology companies, platforms, payment processors and other businesses entering the political marketplace, we apply established political laws to new products, technologies and business models.', 100),
  ('practice.advocacy.body.3', 'Advocacy details', 'Paragraph 3', 'Our role is not simply to identify restrictions. We work with clients to understand what they are trying to accomplish, contextualize the legal risk and develop practical, compliant paths forward.', 101),
  ('practice.nonprofits.body.1', 'Nonprofits details', 'Paragraph 1', 'TPLG advises 501(c)(3) charities and foundations, 501(c)(4) social welfare organizations, 501(c)(6) trade associations, 527 organizations and affiliated political committees on the tax, campaign finance and election laws governing political and issue advocacy.', 102),
  ('practice.nonprofits.body.2', 'Nonprofits details', 'Paragraph 2', 'We counsel organizations on formation and structure, political campaign activity, lobbying, issue advocacy, ballot measure activity, affiliated PACs and other political organizations, funding and disclosure. For organizations operating across jurisdictions or through multiple affiliated entities, we help clients understand how different regulatory regimes interact and structure programs accordingly.', 103),
  ('practice.nonprofits.body.3', 'Nonprofits details', 'Paragraph 3', 'Our lawyers serve as outside counsel to nonprofit organizations and advocacy programs nationwide, helping clients pursue their missions while navigating the legal boundaries applicable to tax-exempt organizations and political activity.', 104),
  ('practice.ethics.body.1', 'Ethics details', 'Paragraph 1', 'TPLG advises public officials, government employees, corporations, lobbyists, government contractors and other organizations interacting with government on lobbying, governmental ethics, conflicts of interest and disclosure requirements. In California, for example, the Political Reform Act regulates lobbying, conflicts of interest, gifts and honoraria, post-government employment and related disclosure obligations.', 105),
  ('practice.ethics.body.2', 'Ethics details', 'Paragraph 2', 'Our work includes lobbying registration and reporting, gifts and honoraria, conflicts of interest, revolving-door restrictions, Statements of Economic Interests, government contracting and pay-to-play requirements. We design multijurisdictional lobbying and political compliance programs and work with clients to develop clearance procedures, internal controls, compliance manuals and training tailored to how their organizations actually operate.', 106),
  ('practice.ethics.body.3', 'Ethics details', 'Paragraph 3', 'We also conduct internal reviews and audits designed to identify issues before they become problems and advise clients when ethics questions arise in connection with particular transactions, government decisions or political activity.', 107),
  ('practice.enforcement.body.1', 'Enforcement details', 'Paragraph 1', 'TPLG represents individuals, campaigns, political committees, corporations, nonprofit organizations and other regulated entities in sensitive audits, investigations, complaints and administrative enforcement proceedings before federal, state and local regulators. The FEC administers and enforces federal campaign finance law, while agencies such as California''s FPPC investigate and enforce campaign finance, lobbying and governmental ethics requirements at the state and local level.', 108),
  ('practice.enforcement.body.2', 'Enforcement details', 'Paragraph 2', 'Our lawyers bring experience from both sides of the regulatory process. We understand how enforcement agencies evaluate complaints, develop investigations and assess potential violations, and we use that perspective to distinguish meaningful risk from theoretical risk, develop the factual record and build strategic defenses.', 109),
  ('practice.enforcement.body.3', 'Enforcement details', 'Paragraph 3', 'We also advise clients before an enforcement matter exists. Through internal audits, compliance reviews, training and risk assessments, we help organizations identify vulnerabilities, strengthen their compliance programs and make informed decisions about issues that may later receive regulatory scrutiny.', 110),
  ('insights.heading.main', 'Insights', 'Heading', 'The political landscape', 111),
  ('insights.heading.emphasis', 'Insights', 'Heading emphasis', 'keeps moving.', 112),
  ('insights.lede', 'Insights', 'Introduction', 'Selected analysis, commentary and coverage involving The Political Law Group.', 113),
  ('insights.red-state-direct-democracy.title', 'Insights', 'WhoWhatWhy: title', 'Red State Legislators Work to Throttle Direct Democracy', 114),
  ('insights.red-state-direct-democracy.publication', 'Insights', 'WhoWhatWhy: publication', 'WhoWhatWhy', 115),
  ('insights.red-state-direct-democracy.date', 'Insights', 'WhoWhatWhy: date', 'September 18, 2026', 116),
  ('insights.red-state-direct-democracy.credit', 'Insights', 'WhoWhatWhy: credit', 'Featuring Emma Olson Sharkey', 117),
  ('insights.florida-ballot-measures.title', 'Insights', 'Common Dreams: title', 'No Ballot Measures Qualified in Florida This Year; That Was Not an Accident', 118),
  ('insights.florida-ballot-measures.publication', 'Insights', 'Common Dreams: publication', 'Common Dreams', 119),
  ('insights.florida-ballot-measures.date', 'Insights', 'Common Dreams: date', 'March 10, 2026', 120),
  ('insights.florida-ballot-measures.credit', 'Insights', 'Common Dreams: credit', 'By Emma Olson Sharkey', 121),
  ('insights.california-redistricting.title', 'Insights', 'Alliance for Justice: title', 'Rules of the Game: California Redistricting and Ballot Measures with Emma Olson Sharkey', 122),
  ('insights.california-redistricting.publication', 'Insights', 'Alliance for Justice: publication', 'Alliance for Justice', 123),
  ('insights.california-redistricting.date', 'Insights', 'Alliance for Justice: date', 'September 17, 2025', 124),
  ('insights.california-redistricting.credit', 'Insights', 'Alliance for Justice: credit', 'Podcast featuring Emma Olson Sharkey', 125),
  ('insights.piraeus-point.title', 'Insights', 'The Coast News Group: title', 'Former Encinitas official’s votes on Piraeus Point likely a conflict, experts say', 126),
  ('insights.piraeus-point.publication', 'Insights', 'The Coast News Group: publication', 'The Coast News Group', 127),
  ('insights.piraeus-point.date', 'Insights', 'The Coast News Group: date', 'March 4, 2025', 128),
  ('insights.piraeus-point.credit', 'Insights', 'The Coast News Group: credit', 'Featuring Tracey Frazier Wigglesworth', 129),
  ('insights.evan-low-campaign-finance.title', 'Insights', 'CalMatters: title', 'California regulators allege this Silicon Valley ex-lawmaker violated campaign finance law dozens of times', 130),
  ('insights.evan-low-campaign-finance.publication', 'Insights', 'CalMatters: publication', 'CalMatters', 131),
  ('insights.evan-low-campaign-finance.date', 'Insights', 'CalMatters: date', 'February 7, 2025', 132),
  ('insights.evan-low-campaign-finance.credit', 'Insights', 'CalMatters: credit', 'Featuring Tracey Frazier Wigglesworth', 133),
  ('insights.lawson-remer-campaign-money.title', 'Insights', 'Voice of San Diego: title', 'Supervisor Lawson-Remer Paid Child Care Bills with Campaign Money', 134),
  ('insights.lawson-remer-campaign-money.publication', 'Insights', 'Voice of San Diego: publication', 'Voice of San Diego', 135),
  ('insights.lawson-remer-campaign-money.date', 'Insights', 'Voice of San Diego: date', 'October 23, 2024', 136),
  ('insights.lawson-remer-campaign-money.credit', 'Insights', 'Voice of San Diego: credit', 'Featuring Tracey Frazier Wigglesworth', 137),
  ('insights.direct-democracy-ballot.title', 'Insights', 'The Hill: title', 'America needs direct democracy more than ever — protect the ballot now', 138),
  ('insights.direct-democracy-ballot.publication', 'Insights', 'The Hill: publication', 'The Hill', 139),
  ('insights.direct-democracy-ballot.date', 'Insights', 'The Hill: date', 'July 27, 2024', 140),
  ('insights.direct-democracy-ballot.credit', 'Insights', 'The Hill: credit', 'Co-authored by Emma Olson Sharkey', 141),
  ('insights.together-sf.title', 'Insights', 'Mission Local: title', 'Mark Farrell consultant texts that TogetherSF head is ‘guiding the ship’', 142),
  ('insights.together-sf.publication', 'Insights', 'Mission Local: publication', 'Mission Local', 143),
  ('insights.together-sf.date', 'Insights', 'Mission Local: date', 'May 9, 2024', 144),
  ('insights.together-sf.credit', 'Insights', 'Mission Local: credit', 'Featuring Nicholas Sanders', 145),
  ('insights.red-state-attorneys-general.title', 'Insights', 'Bolts: title', 'Red State AGs Keep Trying to Kill Ballot Measures by a Thousand Cuts', 146),
  ('insights.red-state-attorneys-general.publication', 'Insights', 'Bolts: publication', 'Bolts', 147),
  ('insights.red-state-attorneys-general.date', 'Insights', 'Bolts: date', 'February 29, 2024', 148),
  ('insights.red-state-attorneys-general.credit', 'Insights', 'Bolts: credit', 'Featuring Emma Olson Sharkey', 149),
  ('insights.sb-county-tax-measure.title', 'Insights', 'Follow Our Courts: title', 'SB County tax measure ruled invalid in appeal', 150),
  ('insights.sb-county-tax-measure.publication', 'Insights', 'Follow Our Courts: publication', 'Follow Our Courts', 151),
  ('insights.sb-county-tax-measure.date', 'Insights', 'Follow Our Courts: date', 'February 21, 2024', 152),
  ('insights.sb-county-tax-measure.credit', 'Insights', 'Follow Our Courts: credit', 'Matter handled by Nicholas Sanders', 153),
  ('insights.ballot-measure-insights.title', 'Insights', 'Alliance for Justice: title', 'Ballot Measure Insights with Emma Olson Sharkey', 154),
  ('insights.ballot-measure-insights.publication', 'Insights', 'Alliance for Justice: publication', 'Alliance for Justice', 155),
  ('insights.ballot-measure-insights.date', 'Insights', 'Alliance for Justice: date', 'January 10, 2024', 156),
  ('insights.ballot-measure-insights.credit', 'Insights', 'Alliance for Justice: credit', 'Podcast featuring Emma Olson Sharkey', 157),
  ('insights.ballot-measure-wars.title', 'Insights', 'Democracy Docket: title', 'The Ballot Measure Wars', 158),
  ('insights.ballot-measure-wars.publication', 'Insights', 'Democracy Docket: publication', 'Democracy Docket', 159),
  ('insights.ballot-measure-wars.date', 'Insights', 'Democracy Docket: date', 'August 7, 2023', 160),
  ('insights.ballot-measure-wars.credit', 'Insights', 'Democracy Docket: credit', 'Co-authored by Emma Olson Sharkey', 161),
  ('insights.weaken-ballot-process.title', 'Insights', 'Salon: title', 'Republicans aim to weaken ballot measure process after progressive victories', 162),
  ('insights.weaken-ballot-process.publication', 'Insights', 'Salon: publication', 'Salon', 163),
  ('insights.weaken-ballot-process.date', 'Insights', 'Salon: date', 'March 15, 2023', 164),
  ('insights.weaken-ballot-process.credit', 'Insights', 'Salon: credit', 'Co-authored by Emma Olson Sharkey', 165),
  ('insights.democrats-voting-strength.title', 'Insights', 'The Washington Post: title', 'The truth about Democrats’ voting strength', 166),
  ('insights.democrats-voting-strength.publication', 'Insights', 'The Washington Post: publication', 'The Washington Post', 167),
  ('insights.democrats-voting-strength.date', 'Insights', 'The Washington Post: date', 'December 8, 2022', 168),
  ('insights.democrats-voting-strength.credit', 'Insights', 'The Washington Post: credit', 'Letter by Emma Olson Sharkey', 169),
  ('insights.ballot-itself.title', 'Insights', 'The New York Times: title', 'On the Ballot This Year: The Ballot Itself', 170),
  ('insights.ballot-itself.publication', 'Insights', 'The New York Times: publication', 'The New York Times', 171),
  ('insights.ballot-itself.date', 'Insights', 'The New York Times: date', 'October 7, 2022', 172),
  ('insights.ballot-itself.credit', 'Insights', 'The New York Times: credit', 'External coverage', 173),
  ('insights.donor-network.title', 'Insights', 'CalMatters: title', 'Force multipliers: How one donor network is pushing the envelope on California campaign money', 174),
  ('insights.donor-network.publication', 'Insights', 'CalMatters: publication', 'CalMatters', 175),
  ('insights.donor-network.date', 'Insights', 'CalMatters: date', 'August 4, 2022', 176),
  ('insights.donor-network.credit', 'Insights', 'CalMatters: credit', 'Featuring Tracey Frazier Wigglesworth', 177),
  ('contact.heading.main', 'Contact', 'Heading', 'Start a conversation.', 178),
  ('contact.heading.emphasis', 'Contact', 'Heading emphasis', 'Political law counsel nationwide.', 179),
  ('contact.lede', 'Contact', 'Introduction', 'Sacramento, California.', 180),
  ('contact.address.street', 'Contact', 'Street address', '1215 K, Suite 2000', 181),
  ('contact.address.locality', 'Contact', 'City, state and ZIP', 'Sacramento, California 95814', 182),
  ('contact.email', 'Contact', 'Email', 'info@tpl.group', 183),
  ('contact.phone', 'Contact', 'Phone', '(916) 674-6440', 184),
  ('global.footer.tagline', 'Global', 'Footer tagline', 'Political law counsel nationwide.', 185)
on conflict (content_key) do update
set
  page = excluded.page,
  label = excluded.label,
  content_value = excluded.content_value,
  sort_order = excluded.sort_order;
